/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2019-03-29 01:45:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class ShowCalendar_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(this, ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }
  private java.lang.String year;
  private java.lang.String month;

  public java.lang.String getYear() {
    return this.year;
  }

  public void setYear(java.lang.String year) {
    this.year = year;
    jspContext.setAttribute("year", year);
  }

  public java.lang.String getMonth() {
    return this.month;
  }

  public void setMonth(java.lang.String month) {
    this.month = month;
    jspContext.setAttribute("month", month);
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    return _jsp_instancemanager;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);
    if( getYear() != null ) 
      _jspx_page_context.setAttribute("year", getYear());
    if( getMonth() != null ) 
      _jspx_page_context.setAttribute("month", getMonth());

    try {
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

int y=1999,m=1;
String[] day=new String[42];
try{
    y=Integer.parseInt(year);
    m=Integer.parseInt(month);
    Calendar rili=Calendar.getInstance();
    rili.set(y,m-1,1);//将日历翻到year 年month月1日,注意0表示1月---11表示12月
    int weekday =rili.get(Calendar.DAY_OF_WEEK)-1;//星期几
    int dayAmount=0;    //某月份天数
    if(m==1||m==3||m==5||m==7||m==8||m==10||m==12)
        dayAmount=31;
    if(m==4||m==6||m==9||m==11)
        dayAmount=30;
    if(m==2)//二月判断
        if(((y%4 == 0)&&(y%100!=0))||(y%400==0))
            dayAmount=29;
        else
            dayAmount=28;

    for(int i=0;i<weekday; i++)
        day[i]="--";
    for(int i=weekday,n=1;i<weekday+dayAmount;i++){
        day[i]=String.valueOf(n);
        n++;
    }

    for(int i=weekday+dayAmount;i<42;i++)
        day[i]="--";
}catch(Exception e){
	out.print("年份或月份不合理");
}

      out.write("\r\n");
      out.write("    <h3>");
      out.print( year);
      out.write('年');
      out.print(month );
      out.write("月的日历:</h3>\r\n");
      out.write("    <table border=1>\r\n");
      out.write("    <tr>\r\n");
      out.write("    <th>星期日</th>\r\n");
      out.write("    <th>星期一</th>\r\n");
      out.write("    <th>星期二</th>\r\n");
      out.write("    <th>星期三</th>\r\n");
      out.write("    <th>星期四</th>\r\n");
      out.write("    <th>星期五</th>\r\n");
      out.write("    <th>星期六</th>\r\n");
      out.write("    </tr>\r\n");
      out.write("    ");
 for(int n=0;n<day.length;n=n+7){
        
      out.write(" <tr> ");

        for(int i=n;i<7+n;i++){
        
      out.write("<td>");
      out.print(day[i] );
      out.write("</td>");

        }
 
      out.write(" </tr> ");

    }
      out.write("\r\n");
      out.write("    </table>");
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
    }
  }
}
